
  name: IOS
  on:
    ['push']

  jobs:
    build-release:
      runs-on: macos-latest
      container:
        image: barichello/godot-ci:3.4.4
      steps:
        - uses: actions/checkout@v2
          with:
            lfs: true

        - name: Build iOS App
          run: |
            mkdir -v -p ./dist
            godot --quiet --export "iOS" ./dist/FallingSquare.ipa

        - name: Upload Android App Bundle
          uses: actions/upload-artifact@v2
          with:
            name: ios
            path: |
              dist/FallingSquare.ipa