
  name: IOS
  on:
    ['push']

  jobs:
    build-release:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
          with:
            lfs: true

        - name: Install godot
          run: brew install --cask godot

        - name: Install template
          run: |
            wget -q https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_export_templates.tpz
            mkdir -p /Users/runner/Library/Application Support/Godot/templates/3.4.4.stable/
            unzip Godot_v3.4.4-stable_export_templates.tpz
            mv templates/* /Users/runner/Library/Application Support/Godot/templates/3.4.4.stable/

        - name: Build iOS App
          run: |
            mkdir -v -p ./dist
            godot --quiet --export "iOS" ./dist/FallingSquare.ipa

        - name: Upload Android App Bundle
          uses: actions/upload-artifact@v2
          with:
            name: ios
            path: |
              dist/FallingSquare.ipa