
name: Release
on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates//${GODOT_VERSION}.stable ~/.local/share/godot/templates//${GODOT_VERSION}.stable
          mkdir -v -p ~/.config/godot/
          cp /root/.config/godot/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres
          mkdir -pv android/build
          mkdir -pv android/plugins
          echo "${GODOT_VERSION}.${GODOT_RELEASE}" > android/.build_version
          unzip ~/.local/share/godot/templates/${GODOT_VERSION}.${GODOT_RELEASE}/android_source.zip -d android/build
          touch android/build/.gdignore
          chmod +x android/build/gradlew


      - name: Prepare android release
        env:
          ANDROID_KEYSTORE: ${{secrets.ANDROID_RELEASE_KEYSTORE}}
          ANDROID_KEYSTORE_USER: ${{secrets.ANDROID_RELEASE_KEYSTORE_USER}}
          ANDROID_KEYSTORE_PW: ${{secrets.ANDROID_RELEASE_KEYSTORE_PW}}
        if: |
          env.ANDROID_KEYSTORE &&
          env.ANDROID_KEYSTORE_USER &&
          env.ANDROID_KEYSTORE_PW
        run: |
          echo $ANDROID_KEYSTORE | base64 --decode > ./production.keystore
          sed 's@keystore/release=".*"@keystore/release="'./production.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="'$ANDROID_KEYSTORE_USER'"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="'$ANDROID_KEYSTORE_PW'"@g' -i export_presets.cfg

      - name: Build
        run: |
          cp /root/.config/godot ~/.config -r
          mkdir -v -p dist/
          godot --quiet --export-debug Android dist/FallingSquare-debug.apk >&-
          godot --quiet --export Android dist/FallingSquare.aab >&-

      - name: Upload android apk
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            dist/FallingSquare.aab
            dist/FallingSquare-debug.apk
 
